class AppStrings {
  static const privacyPolicyContent =
      '''This page lays out Rehlatyuae privacy policy explaining how your personal information is collected, used, and/or disclosed by Rehlatyuae. Please read it carefully. 

This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Rehlatyuae. By accessing or using our Service or by contacting or engaging with us directly, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website and/or direct engagement with us following the posting of changes to this Privacy Policy that does not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
1. Definitions and Key Terms 
   
•	Affiliated Companies: Any person or entity which directly or indirectly controls is controlled by or is under common control with Rehlatyuae, whether by ownership or otherwise
•	Cookie(s): Small amount of data generated by a website and saved by your browser that enables us to identify your browser, use analytics, and remember information about you such as your language preferences or login information
•	Company: The entity responsible for your information under this privacy policy, Rehlatyuae, may be referenced in this document as “company”, “we”, “us”, or “our”. It refers to TRIPXTOURS DMCC, Mazaya Business Avenue BB2, Jumeirah Lake Towers, Dubai, United Arab Emirates.
•	Device: Phones, tablets, computers, or any other internet-connected device that is or can be used to visit and use the Rehlatyuae website or the services it provides 
•	IP Address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet. 
•	Personnel: Individuals employed by or under contract with Rehlatyuae to perform a service on behalf of one of the parties.
•	Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
•	Service(s): The provision of information, recommendations, and services related to travel and leisure, including tools for researching and/or booking attractions, experiences, dining, tours, and cruises, among other leisure-related services.
•	Service Providers: The sellers listed on Rehlatyuae Platform including affiliates and other business partners
•	Third parties: Advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. 
•	Website: www. Rehlatyuae.com 
•	You/your: The end-user
 
2. Application of Privacy Policy 
•	This Privacy Policy applies to our Services – the Website, its associated subdomains, and our application. 
•	By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service. 
•	By using Rehlatyuae or contacting us directly, you signify your acceptance of this Privacy Policy. 
•	If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
•	We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.

3. Information collected and processed by Rehlatyuae
•	 When you access or use our Services, we collect and process information from and about you to provide the Services in a more personalized and relevant way. Some information we collect passively, for example, with our servers or with cookies and/or pixels, or other similar tracking technologies. Some information we collect from different sources entities, including from you, affiliated, business partners, and other independent third-parties. When you use our Services by “clicking-through” from a third-party website or when you visit third-party websites via our Services, those third-parties may share information with us about your use of their Service. Any information that we receive from third-party websites may be combined with the information provided by you.
•	Information collected and processed may include the following: 
o	Contact information, including name, phone number, and postal and email addresses (both hashed and unhashed)
o	Billing and other payment information (such as your bank account information, credit card number, cardholder name, expiration date, authentication code and billing address)
o	Documentation to support travel and planning
o	Username and password
o	Details relating to your account with Rehlatyuae
o	Photos, ratings, reviews, and other social posts you may have provided to us
o	Geolocation information
o	Device information, such as when you accessed our Services and information about the Device used (for example, IP address, software or internet browser used, preferred languages, unique Device identifiers, and advertising identifiers)
o	Online activity, including pages you have visited, content reviewed, and apps reviewed
o	Other information about yourself that you have voluntarily disclosed
o	Communications when you contact our customer service team, including inbound and outbound calls
o	Information that you have provided to third parties including publicly available information, such as name, age-range as well as email addresses. You can control access to this information by altering your privacy settings in those websites or platforms.
•	We may also collect – in instances where you have provided it – information about other travelers or guests, including their email address and other activity or experience-related information. If you are sharing information with us about other individuals, you must obtain their consent and ensure that they have understood and accepted how we will use their personal information as described in this Privacy Policy.
4. Purpose and Use of Collected Information
•	Your Personal Information collected while you access Rehlatyuae is used only for lawful purposes and with an aim to provide you our services to the best of our capabilities. This includes delivering relevant content and tailored experiences. We do not sell or rent this information to anyone nor do we share your information with any third party, unless otherwise provided under the applicable law and specified in this Privacy Policy and/or other than as necessary to fulfill your request.
•	The information collected and processed as per Section 2 above may be used in the following ways: 
o	Registration and Account Management 
	Register and manage your account, including to allow you access to and use of our services
	Facilitate your bookings
	Process payments or credits
	Offer you promotional programs that may include competitions, gift cards, rewards, cash back, and discounts
o	Individualisation and Customisation 
	Notify you about special offers and products or services available from us, our affiliates, or our partners that may be of interest to you
	Tailor your experience, including by making inferences about your interests and preferences based on your activity and customize the ads shown to you both on and off our website
o	Improve our Services
	Use your information for analytical purposes and to enable us to improve our Services
	Provide you with a tailored, optimized experience by grouping users based on, for example, usage, interests and demographics
o	Communication
	Communicate with you or facilitate communication between you and our Service Providers
	Conduct, monitor and record your calls or interactions with us; For example, your communications with our customer service or sales teams, or through our use of pixels and similar technologies to monitor how you interact with our emails to you, such as whether you open or click on content in our emails
	Host your ratings, reviews, posts, photos, videos, and other content
	Respond to your questions and comments
o	Legal Compliance
	Resolve disputes or troubleshoot problems
	Prevent fraud and other potentially prohibited or unlawful activities
	Comply with relevant laws, respond to legal requests, prevent harm, and protect our rights
	Provide payment services, including to detect and prevent money laundering, fraud and security incidents, to comply with legal obligations, and to enforce any applicable terms of service
•	If we make use of any automated decision-making to process your personal information, we also implement the appropriate measures required to safeguard your rights and freedoms including your right to obtain human intervention.
5. Information Sharing 
•	Provision of Services: In order to provide some of our Services, we may use and need to share information with certain Service Providers and/or other Third Parties. This may include advertisers, content sponsors, promotional and marketing partners, and others who provide our content or whose products and services we think may interest you. It can also include Third Parties we entrust to perform functions such as hosting and maintaining our servers and the website, database storage and management, email management, credit card processing, customer service and fulfillment, etc. We may also share this information with our current and future affiliated companies and business partners.
•	Website Analytics: We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technologies such as connection speed, whether you have visited the website in a shared location, and the type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers.
•	Discretionary Disclosure: We may also share your information if we believe, in our sole discretion, that such disclosure is necessary in the following circumstances:
o	To comply with legitimate and enforceable subpoenas, court orders, or other legal processes; to establish or exercise our legal rights; to defend against legal claims; or as otherwise required by law. In such cases, we reserve the right to raise or waive any legal objection or right available to us.
o	To investigate, prevent, or take action regarding illegal or suspected illegal activities; to protect and defend the rights, property, or safety of Rehlatyuae and TRIPXTOURS DMCC, our customers, or others; and in connection with our Terms of Use and other agreements.
o	In connection with a corporate transaction, such as a divestment, merger, consolidation, or asset sale, or in the unlikely event of bankruptcy.
6. Information Storage, Transfer, Deletion, and Retention
•	Your Personal Information is retained on our servers for such a period as may be required to meet the purpose for which such information was collected as described in this Privacy Policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. However, we may retain your Personal Information for a longer period, if in case required by law.
•	Rehlatyuae is incorporated in the United Arab Emirates. However, we offer our Services to users located in multiple jurisdictions. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information. If we transfer your information to other countries, we will use and protect that information as described in This Privacy Policy and in accordance with applicable law.
•	When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.
7. Information Security 
•	We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server and enforce various physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information.
•	All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. 
•	People, security and encryption systems are not foolproof. Additionally, people can commit intentional crimes, make mistakes, or fail to follow policies. We cannot, as a result, ensure or warrant the absolute security of any information you transmit to Rehlatyuae or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
8. Update information
•	The rights you have to request updates or corrections to the information Rehlatyuae collects depend on your relationship with Rehlatyuae. Personnel may update or correct their information as detailed in our internal company employment policies.
•	You have the right to request the restriction of certain uses and disclosures of your information subject to the limits imposed in Section 7 as follows:
o	Update or correct your personally identifiable information
o	Change your preferences with respect to communications and other information you receive from us 
o	Delete the personally identifiable information maintained about you on our systems by canceling your account.
•	Any updates, corrections, changes, and deletions may have no effect on other information that we maintain or provide to Third Parties in accordance with this Privacy Policy prior to such update, correction, change, or deletion.
•	To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the security of your unique password and account information at all times.
•	We inform you that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.
9. Governing Law and Choice of Forum 
•	This Privacy Policy is governed by the laws of the United Arab Emirates without regard to its conflict of laws provision. The laws of the United Arab Emirates, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.
•	You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under the Privacy Shield, or the Swiss-US framework .
10. External Links
•	This Privacy Policy only applies to the Services as defined in Section 1. The Services and/or the Service Providers may contain links to other external websites not operated or controlled by Rehlatyuae. We are not responsible for the content, accuracy, or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. 
•	Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
11. Children's Data 
•	Our Services are not intended for nor address children, which we consider to be: (i) individuals that are 13 years of age or under, or the age of privacy consent in your jurisdiction; or (ii) when processing data on the basis of a contract, the age of legal capacity to enter into the agreement.
•	We will only knowing collect or process information belonging to children under very limited circumstances such as when personal information is required as part of the provision of a Service; for example when personal information is required as part of a ticketing reservation.
•	We will only knowingly collect or process information belonging to children if it is provided by and with the consent of a parent or guardian. 
•	If you are a parent or guardian and you are aware that your child has provided us with Personal Information, please contact us. If we become aware that we have processed the personal information of a child without the valid consent of a parent or guardian, we will take steps to delete the Personal Information from our servers.
12. Privacy Policy Changes
•	We may update this Privacy Policy in the future. If we believe any changes are material, we will let you know by doing one or more of the following: 
o	Sending you a communication about the changes
o	Placing a notice on the website 
o	Posting an updated Privacy Policy on the website. 
•	We will note at the top of this Statement when it was most recently updated. We encourage you to check back from time to time to review the most current version and to periodically review this Policy for the latest information on our privacy practices.
•	Changes to this Privacy Policy are applicable and effective when they are posted on this page
13. Contact
•	If you have any doubts regarding the details of this Privacy Policy, please contact us at info@ Rehlatyuae.com 
•	If you have any data privacy related requests, such as accessing or deleting your Personal Information, please contact us at info@ Rehlatyuae.com 
''';

  static const termsConditionsContent = '''General Terms

By accessing and placing an order with Rehlatyuae, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Rehlatyuae.

Under no circumstances shall Rehlatyuae team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Rehlatyuae team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.

Rehlatyuae will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the resource rights to change prices and revise the usage policy at any moment.

License

Rehlatyuae grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.

These Terms & Conditions are a contract between you and Rehlatyuae (referred to in these Terms & Conditions as “Rehlatyuae”, “us”, “we” or “our”), the provider of the Rehlatyuae website and the services accessible from the Rehlatyuae website (which are collectively referred to in these Terms & Conditions as the “Rehlatyuae Service”).

You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Rehlatyuae Service. In these Terms & Conditions, “you” refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.

Definitions and key terms

To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:
•	Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
•	Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to TRIPXTOURS DMCC, Mazaya Business Avenue BB2, Jumeirah Lake Towers, Dubai, United Arab Emirates that is responsible for your information under this Terms & Conditions.
•	Country: where Rehlatyuae or the owners/founders of Rehlatyuae are based, in this case is United Arab Emirates
•	Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Rehlatyuae and use the services.
•	Service: refers to the service provided by Rehlatyuae as described in the relative terms (if available) and on this platform.
•	Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
•	Website: Rehlatyuae."'s" site, which can be accessed via this URL: www.Rehlatyuae.com
•	You: a person or entity that is registered with Rehlatyuae to use the Services.
Restrictions
You agree not to, and you will not permit others to:
•	License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.
•	Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.
•	Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Rehlatyuae or its affiliates, partners, suppliers or the licensors of the website.
Modifications, Cancellations, and Refunds
•	Rehlatyuae is not liable to any refunds in credit or cash from modifications or cancellations. You access and use listings entirely at your own risk and subject to the supplier's terms and conditions.
•	All matters concerning modifications and/or cancellations of bookings are decided and/or determined by the Supplier. Given that the purchase of any Service is a contract between you and the Supplier, Rehlatyuae does not frame the terms of modification/cancellation of the bookings or take any decision regarding modification/cancellation of the bookings, unless agreed to the contrary between Rehlatyuae and the concerned Supplier.
•	Please refer to the specific terms and conditions of a concerned listing to confirm whether modification/cancellation is available and, if available, how to proceed with it. 
•	Suppose a Booking has been modified/cancelled by you as per the terms mentioned herein and as per the terms of the Supplier. In that case, Rehlatyuae will, subject to receipt of the refund amount from the Supplier, refund the applicable amount to you. 
o	Under no circumstances Rehlatyuae will pay you the refund until Rehlatyuae receives it from the Supplier. 
o	Once Rehlatyuae receives the refund amount from the Supplier, Rehlatyuae will endeavor to initiate the refund within seven (7) days of receipt from the Supplier. 
o	As a default practice, Rehlatyuae processes the refund amount to the original source of payment. 
o	In case the original source of payment is unavailable, you can choose to receive the refund in the form of Rehlatyuae Credits to the Rehlatyuae Account of the user. These Rehlatyuae Credits are neither transferable nor can be refunded or redeemed in the form of cash. Rehlatyuae reserves the right to make changes to the usage terms of Rehlatyuae Credits, including but not limited to, value, usage, and validity without prior notice or intimation.
•	If you make a booking using a promotion code, or if you accept a discount or special-offer price during the check-out process, you may invalidate your discount or special-offer price by modifying/cancelling your Booking. If you are due a refund, Rehlatyuae will process it to you after adjusting such discount or special offer availed at the time of booking.
•	Refunds are not possible once a Service has begun or for any part of the Service package, including accommodation, meals, or other services that you have already used.
•	A Supplier may reserve the right to modify a booking post-purchase, which may involve alterations to the date, price, inclusions, coverage, age requirements, or any other aspects of the Service. Rehlatyuae will strive to inform you promptly of any such adjustments once made aware of them. Your rights regarding these changes with respect to the Supplier will be determined by the Supplier Terms. Rehlatyuae bears no responsibility for any losses, expenses, costs, damages, or injuries resulting from or related to such changes made to the booking, neither to you nor any other individual.
•	Pursuant to such alteration(s), if the Supplier either cancels the Booking or allows you to cancel it, Rehlatyuae will make efforts to process the refund amount received from the Supplier within seven (14) days of its receipt. If the Supplier permits you to amend the Booking in line with the changes, any relevant information we obtain will be promptly conveyed to you upon our awareness. Rehlatyuae assumes no liability towards you or any other party for any losses, expenses, costs, or damages arising from 
o	your inability to modify the bookingthe
o	Supplier's failure to communicate about the modification of the booking with either us or you, or 
o	The services used following the modification of the booking.
•	Rehlatyuae reserves the right, at its sole discretion, to deem it necessary or beneficial for the protection of our interests, the Supplier's interests, and/or your interests, to withdraw our services, thereby superseding the Supplier's cancellation policy. Additionally, we may, at our sole discretion, opt to facilitate a partial or full refund of the amounts charged to you. By agreeing to these Terms of Use, you acknowledge that we bear no liability for such cancellations or refunds.
•	In any scenario of cancellation of any booking, you agree and understand that Rehlatyuae shall only be liable to process the refund of the booking amount upon receiving the same from the Supplier. You also agree that all liabilities against any booking are attributable to the Supplier. Rehlatyuae will not undertake any other liability of any sort including but not limited to any incidental losses incurred by you.
Your Suggestions

Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") shall be provided by you to Rehlatyuae with respect to the website remain the sole and exclusive property of Rehlatyuae.

Rehlatyuae shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.

Your Consent

We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.

Links to Other Websites

These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Rehlatyuae. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.

Cookies

Rehlatyuae uses “Cookies” to identify the areas of our website that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of cookies. However, if you disable cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.

Changes To Our Terms & Conditions

You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which are contained in your account.

If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.

Modifications to Our website

Rehlatyuae reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.

Updates to our website

Rehlatyuae may from time to time provide enhancements or improvements to the features/functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications (“Updates”).

Updates may modify or delete certain features and/or functionalities of the website. You agree that Rehlatyuae has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website to you.

You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms and conditions of this Agreement.

Third-Party Services

We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third-Party Services”).

You acknowledge and agree that Rehlatyuae shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Rehlatyuae does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.

Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.

Term and Termination

This Agreement shall remain in effect until terminated by you or Rehlatyuae.

Rehlatyuae may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.

This Agreement will terminate immediately, without prior notice from Rehlatyuae, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website and all copies thereof from your computer.

Upon termination of this Agreement, you shall cease all use of the website and delete all copies of the website from your computer.

Termination of this Agreement will not limit any of Rehlatyuae's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.

Copyright Infringement Notice

If you are a copyright owner or such owner's agent and believe any material on our website constitutes an infringement of your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.

Indemnification

You agree to indemnify and hold Rehlatyuae and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.

No Warranties

The website is provided to you “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Rehlatyuae, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website , including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Rehlatyuae provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, systems or services, operate without interruption , meet any performance or reliability standards or be error free or that any errors or
defects can or will be corrected.

Without limiting the foregoing, neither Rehlatyuae nor any Rehlatyuae's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website, or the information, content, and materials or products included thereon; (ii) that the website will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website; or (iv) that the website, its servers, the content, or e-mails sent from or on behalf of Rehlatyuae are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.

Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.

Limitation of Liability

Notwithstanding any damages that you might incur, the entire liability of Rehlatyuae and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website.

To the maximum extent permitted by applicable law, in no event shall Rehlatyuae or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Rehlatyuae or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.

Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.

Severability

If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.

This Agreement, together with the Privacy Policy and any other legal notices published by Rehlatyuae on the Services, shall constitute the entire agreement between you and Rehlatyuae concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Rehlatyuae."'s" failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND REHLATYUAE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.

Waiver

Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's to exercise such right or require such ability performance at any time thereafter nor shall be the waiver of a breach constitutes waiver of any subsequent breach. Or failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.

Amendments to this Agreement

Rehlatyuae reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.

By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Rehlatyuae.

Entire Agreement

The Agreement constitutes the entire agreement between you and Rehlatyuae regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Rehlatyuae.

You may be subject to additional terms and conditions that apply when you use or purchase other Rehlatyuae's services, which Rehlatyuae will provide to you at the time of such use or purchase.

Updates to Our Terms

We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.

Intellectual Property

The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Rehlatyuae, its licensors or other providers of such material and are protected by United Arab Emirates and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Rehlatyuae, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.

Agreement to Arbitrate

This section applies to any dispute EXCEPT IT DOESN'T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR Rehlatyuae."'s" INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and Rehlatyuae concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law.

Notice of Dispute

In the event of a dispute, you or Rehlatyuae must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: hello@Rehlatyuae.com. Rehlatyuae will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Rehlatyuae will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Rehlatyuae may commence arbitration.

Binding Arbitration

If you and Rehlatyuae don't resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.

Submissions and Privacy

In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Rehlatyuae without any compensation or credit to you whatsoever. Rehlatyuae and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.

Promotions

Rehlatyuae may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.

Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.

Typographical Errors

In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price . We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.

Miscellaneous

If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of Rehlatyuae. Rehlatyuae will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Rehlatyuae operates and controls the Rehlatyuae Service from its offices in the United Arab Emirates. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Rehlatyuae Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate the Rehlatyuae Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Rehlatyuae concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.

Disclaimer

Rehlatyuae is not responsible for any content, code or any other imprecision. Rehlatyuae does not provide warranties or guarantees. In no event shall Rehlatyuae be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.

The Rehlatyuae Service and its contents are provided “as is” and “as available” without any warranty or representations of any kind, whether express or implied. Rehlatyuae is a distributor and not a publisher of the content supplied by third parties; As such, Rehlatyuae exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Rehlatyuae Service. Without limiting the foregoing, Rehlatyuae specifically disclaims all warranties and representations in any content transmitted on or in connection with the Rehlatyuae Service or on sites that may appear as links on the Rehlatyuae Service, or in the products provided as
a part of, or otherwise in connection with, the Rehlatyuae Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Rehlatyuae or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Rehlatyuae does not warrant that the Rehlatyuae Service will be uninterrupted, uncorrupted, timely, or error-free.

User Responsibility and Assumption of Risk
•	You are responsible and liable for your actions and omissions and are also responsible for the actions and omissions of anyone participating in the service you book through Rehlatyuae. For example, this means: 
o	You are responsible for leaving the venue of a service in the same or substantially the same condition it was in when you arrived; 
o	You must act with integrity, treat others at the place of the service with respect
o	You always comply with all applicable laws and any terms or rules as may be set out by the Supplier. 
Your failure to comply with the applicable local laws or terms set out by the Supplier may result in the Supplier asking you to leave/exit the service or attraction or any other action as per law.
•	You acknowledge that the activities following the Booking carry inherent risks and accordingly agree that, to the maximum extent permitted by applicable law, you assume the entire risk arising out of your access to and use of the Rehlatyuae platform, participation in any service, and/ or any other interaction you have with other persons at the location of the Service or online. This means you are responsible to analyze and understand that the service chosen by you for the booking is suitable for you by all means and manners. For example, services may carry the risk of illness, bodily injury, disability, or death, and you freely and willfully assume those risks by choosing to participate in those services. 
•	Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions. 
•	In the unlikely event that a third party reservation is available when you place an order but becomes unavailable prior to check-in or use, your sole remedy will be to contact the supplier to make alternative arrangements or to cancel your reservation. 
•	If you book a reservation with a third-party supplier, then in addition to this Agreement, you agree to review and be bound by the supplier's terms and conditions of purchase and website use, privacy policy, and any other rules or policies related to the supplier's site or property. Your interactions with third-party suppliers are at your own risk. Rehlatyuae will have no liability with respect to the acts, omissions, errors, representations, warranties, breaches or negligence of any third-party suppliers or for any personal injuries, death, property damage, or other damages or expenses resulting from your interactions with third parties. -party suppliers.
•	Scammers and fraudsters may employ various phishing techniques to illicitly obtain your personal and confidential sensitive data, such as payment information, with an aim to deceive and defraud. These techniques may involve the creation of fake websites, messages, emails, and more. We strongly recommend remaining vigilant and aware of such schemes. Should you fall victim to any phishing endeavors carried out in the name of Rehlatyuae, we kindly request that you report such an incident to hello@Rehlatyuae.com. We also advise you to promptly report such transactions to your bank or any other relevant authority as may be required by law. 
•	We strongly advise exercising caution to ensure that you are engaging with Rehlatyuae through our official and verified communication channels. You have the responsibility to ensure that you do not open or engage with imitators or impersonators. Rehlatyuae cannot be held responsible for any scams or fraudulent activities carried out by such impersonators or external third parties.

Official Channels:
•	Website - Rehlatyuae.com
•	Phone - +971 4 341 7419
•	Email - support@Rehlatyuae.com
''';

  static const appLogo = "assets/images/Group.svg";
  static const ourPartnersLogo = "assets/images/download 1.png";
  static const whyChooseUsFastBookingImage = "assets/images/Vector.png";
  static const whyChooseUsEasyToShopImage = "assets/images/Vector(1).png";
  static const whyChooseUs247SupportImage = "assets/images/Group(1).png";
  static const whyChooseUsUniqueexPerienceImage = "assets/images/Group(2).png";
  static const weHelpYouMakeBestTripImage1 = "assets/images/Rectangle 9897.png";
  static const weHelpYouMakeBestTripImage2 = "assets/images/Rectangle 9899.png";
  static const weHelpYouMakeBestTripImage3 = "assets/images/Rectangle 9898.png";
  static const searchTextFieldHintText = "Search by activities...";
  static const textButtonNameOfHomeScreen = "View all";
  static const categoriesTitle = "Categories";
  static const topDestinationTitle = "Top Destinations";
  static const bestOffersTitle = "Best Offers";
  static const bestTripsTitle = "Best Trips";
  static const popularExperiencesTitle = "Popular Experiences";
  static const ourBlogTitle = "Our Blog";
  static const ourPartnerTitle = "Our Partner";
  static const whyChooseUsTitle = "Why Choose Us";
  static const whyChooseUsFastBooking = "Fast booking";
  static const whyChooseUsFastBookingDescription =
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.";
  static const whyChooseUsEasyToShop = "Easy to Shop";
  static const whyChooseUsEasyToShopDescription =
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.";
  static const whyChooseUs247Support = "24/7 Support";
  static const whyChooseUs247SupportDescription =
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.";
  static const whyChooseUsUniqueexPerience = "Unique experience";
  static const whyChooseUsUniqueexPerienceDescription =
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.";
  static const weHelpYouMakeBestTrip = "We Help You Make Best Trip";
  static const weHelpYouMakeBestTripDescription =
      "Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada";
  static const weHelpYouMakeBestTripSecondDescription =
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.";
  static const actionButtonName = "Explore More";
  static const reviewTitle = "Our Client Reviews";
  static const subscribeToNewsletterTitle = "Subscribe to Newsletter";
  static const reviewTextFieldName = "Your Name";
  static const reviewTextFieldEmail = "Your Email";
  static const reviewActionButtonName = "Send";
  static const copyRight = "Copyright ©2024. All Rights Reserved. — by Rehlatyuai";
  static const profile = "Profile";
  static const edit = "Edit";
  static const about = "About";
  static const fullName = "Full Name";
  static const email = "Email";
  static const phone = "Phone";
  static const dateOfBirth = "Date Of Birth";
  static const editProfile = "Edit Profile";
  static const save = "Save";
  static const forgotPassword = "Forgot Password?";
  static const enterYourInformation = "Enter your information's below or login with a other account";
  static const tryAnotherWay = "Try another way";
  static const send = "Send";
  static const verification = "Verification";
  static const checkYourEmail = "Check your email. We’ve sent you the PIN at your email.";
  static const didYouReceive = "Did you receive any code?";
  static const verify = "Verify";
  static const updatePassword = "Update Password";
  static const youCanNowUpdate = "You can now update your password...!";
  static const newPassword = "New Password";
  static const renterPassword = "R-enter Password";
  static const paymentOptions = "Payment Options";
  static const yourDateBooking = "Your date booking";
  static const selectDate = "Select a date";
  static const selectNumberTicket = "Select Number off ticket";
  static const adult = "Adult";
  static const above4Yrs = "Above 4 yrs";
  static const children = "Children";
  static const under3Yrs = "Under 3 yrs";
  static const youHaveCoupon = "You Have Coupon!";
  static const yourCoupon = "Your Coupon!";
  static const description = "Description";
  static const pleaseInsertAllNotes = "Please insert all notes";
  static const nextPayment = "Next payment";
  static const orderSummary = "Order Summary";
  static const totalAmount = "Total Amount";
  static const creditDebitCards = "Credit & Debit Cards";
  static const addNewCard = "Add New Card";
  static const payment = "Payment";
}
